<?php

namespace App\Enums;

enum EventType: string
{
    case DEFAULT = "DEFAULT";
    case TEST = "TEST";

    case AIRTIME_PURCHASE = "AIRTIME_PURCHASE";
    case AIRTIME_PURCHASE_FAILURE = "AIRTIME_PURCHASE_FAILURE";

    case UTILITY_PAYMENT = "UTILITY_PAYMENT";
    case UTILITY_PAYMENT_FAILURE = "UTILITY_PAYMENT_FAILURE";

    case SUBSCRIPTION_PAYMENT = "SUBSCRIPTION_PAYMENT";
    case SUBSCRIPTION_EXPIRY = "SUBSCRIPTION_EXPIRY";

    case VOUCHER_PURCHASE = "VOUCHER_PURCHASE";
    case VOUCHER_REFUND = "VOUCHER_REFUND";

    case MERCHANT_PAYMENT = "MERCHANT_PAYMENT";

    case WITHDRAWAL_PAYMENT = "WITHDRAWAL_PAYMENT";
    case WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE";

    case PAYMENT_FAILURE = "PAYMENT_FAILURE";

    case REFERRAL_INVITE = "REFERRAL_INVITE";
    case REFERRAL_JOINED = "REFERRAL_JOINED";

    case ERROR_ALERT = "ERROR_ALERT";
    case SP_REQUEST_FAILURE = "SP_REQUEST_FAILURE";
    case STATUS_UPDATE = "STATUS_UPDATE";
}
