name: Security Checker

on:
  push:
    branches:
      - develop

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db
      - uses: symfonycorp/security-checker-action@v4
        with:
          disable-exit-code: 1
        id: security-check
      - name: Display the vulnerabilities as JSON
        run: echo ${{ steps.security-check.outputs.vulns }}
